name: Lint Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix all binary permissions
        # Adding the /* at the end targets the files inside the folder
        run: chmod +x ./node_modules/.bin/*

      - name: Run HTML linter
        run: npx htmlhint .

      - name: Run CSS linter
        run: npm run lint:css

      - name: Run JS linter
        run: npm run lint:js
        
      - name: Run Automated Tests
        run: npm test