name: Lint Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install HTMLHint globally
        run: npm install -g htmlhint

      - name: Run HTML linter
        run: htmlhint .

      - name: Run CSS linter
        run: npm run lint:css

      - name: Run JS linter
        run: npm run lint:js